name: Deploy:Prod

on: 
  push:
    branches:
      - master

jobs:
  deploy_to_live:
    name: Deploy PROD hosting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Yarn
        run: npm install yarn@latest -g
      - name: Install Firebase Tools
        run: npm install firebase-tools -g
      - name: Install dependencies
        run: yarn
      - name: Run build
        env: 
          CRISP_WEBSITE_ID: ${{ secrets.CRISP_WEBSITE_ID }}
          GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
        run: yarn generate
      - name: Run deploy
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting -P ${{ secrets.FIREBASE_APP_ID }}